### ISSUE TITLE
System.ArgumentException

### ISSUE THREAD

**Issue by marcelmedina** [karl-sjogren/robots-txt-middleware#4]
Every time crawlers raise a HEAD request to the root:

**HEAD /**

An exception is raised:
**An item with the same key has already been added.**

Problem Id | System.ArgumentException at RobotsTxt.RobotsTxtMiddleware+<Invoke>d__4.MoveNext |  
-- | -- | --
Assembly | RobotsTxtCore, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null

**Comment by karl-sjogren** [comment]
If the request goes to `/robots.txt` this middleware will kick in otherwise it will just let the next middleware take over. So it should have no impact on other routes then `/robots.txt`.

https://github.com/karl-sjogren/robots-txt-middleware/blob/c3c8c19fb779f4f56d8887a822ae41aa1200c278/src/RobotsTxt/RobotsTxtMiddleware.cs#L17-L27

My guess here is that there is something in a later middleware that throws this error and it bubbles up to this one (`await _next.Invoke(context);` on L26 actually invokes the next middleware which could throw an exception).

Can you reproduce it by simulating a HEAD request to your site? Something like the below call.

    curl --head 'https://www.yoursite.com/' --header 'User-Agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'

If so then try removing the robotstxt middleware and see if it still crashes (which might give you a better stacktrace to the actual error).

**Comment by marcelmedina** [comment]
Thanks @karl-sjogren for the reply.

Indeed when I removed the robots.txt middleware, and tested it, the exception was still occurring.

In my case it was a HTTP 405 that was raising the exception, because HEAD was not allowed by the API.

**Comment by karl-sjogren** [comment]
Thats great to hear! I'll go ahead and close this issue then.
